version: '3.1'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scrapjob
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5

  myapp:
    container_name: myapp
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/scrapjob
    ports:
      - "8081:8081"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
